### ISSUE TITLE
std::option::Option<sycamore::prelude::View<_>> doesn't implement std::fmt::Display

### ISSUE THREAD

**Issue by l1x** [sycamore-rs/sycamore#580]
**Describe the bug**

Trying to compile the todomvc example and get this error:

```Rust
❯ cargo build
   Compiling radmin v0.1.0 (/Users/l1x/code/datadeft/datadeft/frontend/radmin)
error[E0277]: `std::option::Option<sycamore::prelude::View<_>>` doesn't implement `std::fmt::Display`
   --> src/main.rs:146:5
    |
146 | /     view! { cx,
147 | |         div(class="todomvc-wrapper") {
148 | |             section(class="todoapp") {
149 | |                 Header {}
...   |
156 | |         }
157 | |     }
    | |_____^ `std::option::Option<sycamore::prelude::View<_>>` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<sycamore::prelude::View<_>>`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = help: the following other types implement trait `IntoView<G>`:
              &sycamore::prelude::View<G>
              sycamore::prelude::View<G>
    = note: required for `std::option::Option<sycamore::prelude::View<_>>` to implement `IntoView<_>`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0271]: type mismatch resolving `<G as GenericNode>::EventType == KeyboardEvent`
   --> src/main.rs:195:5
    |
195 | /     view! { cx,
196 | |         header(class="header") {
197 | |             h1 { "todos" }
198 | |             input(class="new-todo",
...   |
203 | |         }
204 | |     }
    | |_____^ expected struct `Event`, found struct `KeyboardEvent`
    |
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `std::option::Option<sycamore::prelude::View<_>>` doesn't implement `std::fmt::Display`
   --> src/main.rs:272:5
    |
272 | /     view! { cx,
273 | |         li(class=class()) {
274 | |             div(class="view") {
275 | |                 input(
...   |
295 | |         }
296 | |     }
    | |_____^ `std::option::Option<sycamore::prelude::View<_>>` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<sycamore::prelude::View<_>>`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = help: the following other types implement trait `IntoView<G>`:
              &sycamore::prelude::View<G>
              sycamore::prelude::View<G>
    = note: required for `std::option::Option<sycamore::prelude::View<_>>` to implement `IntoView<_>`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `std::option::Option<sycamore::prelude::View<_>>` doesn't implement `std::fmt::Display`
   --> src/main.rs:384:5
    |
384 | /     view! { cx,
385 | |         footer(class="footer") {
386 | |             span(class="todo-count") {
387 | |                 strong { (app_state.todos_left()) }
...   |
401 | |         }
402 | |     }
    | |_____^ `std::option::Option<sycamore::prelude::View<_>>` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<sycamore::prelude::View<_>>`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = help: the following other types implement trait `IntoView<G>`:
              &sycamore::prelude::View<G>
              sycamore::prelude::View<G>
    = note: required for `std::option::Option<sycamore::prelude::View<_>>` to implement `IntoView<_>`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0271, E0277.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `radmin` due to 4 previous errors
```
**To Reproduce**

1. Go to https://github.com/sycamore-rs/sycamore/tree/master/examples/todomvc
2. Try to compile with version 0.8

**Expected behavior**

A working example

**Environment**

- Sycamore: [0.8.x]
- OS: [e.g. MacOS]
- Rust: 1.67

**Comment by lukechu10** [comment]
The example which you linked too is meant to work only for master branch. If you want to see the v0.8 version, you'll need to go to the branch/tag dropdown and select the version that you want.

**Comment by l1x** [comment]
thanks @lukechu10 !
